### ISSUE TITLE
Question about EdgeRand mechanism?

### ISSUE THREAD

**Issue by scottshufe** [AI-secure/DP-GCN#4]
Thanks for your excellent work first!

In your paper, "EdgeRand algorithm first randomly chooses the cells to perturb and then randomly choose the target value from {0, 1} for each cell to be perturbed".
Does it mean that EdgeRand may introduce a large amount of new edges into the original graph? Because a graph is always "sparse" and the probability of an entry of the adjacency matrix  equals "1" is far less than 0.5.

Best wishes.

**Comment by ghost** [comment]
In our paper, we provide concrete discussions on the level of sparsity, its relationship to the privacy budget, increased density of the graph, etc. Please refer to the paragraphs before and after Theorem 4 for details.

**Comment by scottshufe** [comment]
Thanks, I have found these content in the paper. Sorry, I actually dismissed many details.
